### ISSUE TITLE
依赖失败

### ISSUE THREAD

**Issue by djloops** [crawlab-team/crawlab-core#3]
依赖的仓库github.com/linxGnu/gumble被删除了，导致go build失败
<img width="909" alt="image" src="https://user-images.githubusercontent.com/16716168/192720825-cfdaf6f7-ffb2-4064-a2ea-ef4a135234fa.png">

**Comment by tikazyq** [comment]
好家伙，看起来得自己造轮子

**Comment by djloops** [comment]
> 好家伙，看起来得自己造轮子

学习目的😂，大佬把本地仓库上传下么

**Comment by okki-dev1** [comment]
@djloops 请问这个问题解决了吗😓

**Comment by okki-dev1** [comment]
官网的proxy里面有缓存 GOPROXY=https://proxy.golang.org/
