### ISSUE TITLE
python dependencies parsing error

### ISSUE THREAD

**Issue by skiloop** [crawlab-team/crawlab-core#4]
e.g.  expect 'crawlab-sdk' but got  'crawlab', and dependency fails to install.

the regex expression in function _getDependenciesRequirementsTxt from env_deps.go cannot cover some special char like '-'.

```go
	// regex pattern
	pattern, err := regexp.Compile("(\\w+)([=<>]=.*)?")
	if err != nil {
		return nil, trace.TraceError(err)
	}
```

**Comment by tikazyq** [comment]
Hi, can you provide more details?

**Comment by skiloop** [comment]
> 

this is one of my requirements.txt for example:
```
lxml>=4.9.0
Scrapy>=2.6.1
itemadapter>=0.6.0
crawlab-sdk>=0.6.0
scrapy-redis>=0.7.3
```
then dependencies parsed by crawlab are
```text
lxml
scrapy
crawlab
redis
scrapy
```

crawlab-sdk and scrapy_redis fail to be parsed correctly
